# This is a base file on top of which we build the Image
FROM node:alpine 
# Copy our files into the app folder of the image (IMG also has a file system)
COPY . /app
# What commands to execute 
CMD node app/app.js
# Alternatively we can specify our working directory
# WORKDIR /app
# CMD node app.js
 
